### ISSUE TITLE
No longer works

### ISSUE THREAD

**Issue by zanderwar** [terrybrashaw/Overust#1]
Hey the current RCON is being phased out and this application no longer works out-of-the-box, could you  please look into getting this working with web rcon now via Websockets 

`ws://255.255.255.255:49016/myrconpassword`

**Comment by terrybrashaw** [comment]
Hey, I no longer play Rust so I don't intend to maintain Overust. It was never really feature-complete anyway and I never intended it to be used by the public.

I should probably put that in the README...
